package module_09.OOP2

fun main() {
    println("=".repeat(25) + " BLACK " + "=".repeat(25))
    val black = Black()
    black.putInCard(1500.00)
    black.infoFunds()
    black.billPay(110.00)
    black.infoBalance()

    println("=".repeat(25) + " SUPREME " + "=".repeat(25))
    val supreme = Supreme()
    supreme.putInCard(20000.00)
    supreme.infoBalance()
    supreme.billPay(7600.00)
    supreme.infoBalance()

    println("=".repeat(25) + " DEBIT " + "=".repeat(25))
    val debitCard = DebitCard()
    debitCard.putInCard(50000.0)
    debitCard.infoFunds()
    debitCard.billPay(16000.0)
    debitCard.infoFunds()

    println("=".repeat(25) + " PLATINUM " + "=".repeat(25))
    val platinum = Platinum(accumulation = 2.0)
    platinum.setCreditLimit(10000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(5000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.putInCard(8000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(2000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(4000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(3000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(4000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.putInCard(8000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.putInCard(8000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(6000.0)
    platinum.infoFunds()
    platinum.infoBalance()
    platinum.billPay(16000.0)
    platinum.infoFunds()
    platinum.infoBalance()

    println("=".repeat(25) + " DRIVE " + "=".repeat(25))
    val drive = Drive(cashback = 2.0)
    drive.setCreditLimit(10000.0)
    drive.infoFunds()
    drive.infoBalance()
    drive.billPay(5000.0)
    drive.infoFunds()
    drive.infoBalance()
    drive.putInCard(8000.0)
    drive.infoFunds()
    drive.infoBalance()
    drive.billPay(20000.0)
    drive.infoFunds()
    drive.infoBalance()

    println("=".repeat(25) + " CREDIT " + "=".repeat(25))
    val creditCard = CreditCard()
    creditCard.setCreditLimit(10000.0)
    creditCard.infoFunds()
    creditCard.infoBalance()
    creditCard.billPay(5000.0)
    creditCard.infoFunds()
    creditCard.infoBalance()
    creditCard.putInCard(8000.0)
    creditCard.infoFunds()
    creditCard.infoBalance()
    creditCard.billPay(5000.0)
    creditCard.infoFunds()
    creditCard.infoBalance()
    creditCard.billPay(3000.0)
    creditCard.infoFunds()
    creditCard.infoBalance()
}